export const SESSION_ID = process.env.WORKSHOP_SESSION_CODE || "johari-2026";

export const PARTICIPANTS = [
  { id: "ast", name: "Ast" },
  { id: "mike", name: "Mike" },
  { id: "armen", name: "Armen" },
  { id: "sargis", name: "Sargis" },
  { id: "krist", name: "Krist" },
  { id: "shushan", name: "Shushan" },
  { id: "ani", name: "Ani" }
] as const;

export const REQUIRED_SELF_COUNT = 10;
export const REQUIRED_PEER_COUNT = 15;
export const TOP_RESULT_COUNT = 8;

export const ADJECTIVES = [
  { id: "adj-001", label: "ընդունակ" },
  { id: "adj-002", label: "պատրաստակամ" },
  { id: "adj-003", label: "հզոր" },
  { id: "adj-004", label: "երջանիկ" },
  { id: "adj-005", label: "մտերմիկ" },
  { id: "adj-006", label: "արկածասեր" },
  { id: "adj-007", label: "աջակցող" },
  { id: "adj-008", label: "հպարտ" },
  { id: "adj-009", label: "ագրեսիվ" },
  { id: "adj-010", label: "հումորով" },
  { id: "adj-011", label: "հանգիստ" },
  { id: "adj-012", label: "անշահախնդիր" },
  { id: "adj-013", label: "իդեալիստ" },
  { id: "adj-014", label: "բռնակալ" },
  { id: "adj-015", label: "ինքնուրույն" },
  { id: "adj-016", label: "վստահելի" },
  { id: "adj-017", label: "ազդեցիկ" },
  { id: "adj-018", label: "հավատացյալ" },
  { id: "adj-019", label: "սրամիտ" },
  { id: "adj-020", label: "հոգատար" },
  { id: "adj-021", label: "ստեղծագործ" },
  { id: "adj-022", label: "ռիսկի դիմող" },
  { id: "adj-023", label: "պատասխանատու" },
  { id: "adj-024", label: "ուրախ" },
  { id: "adj-025", label: "ոգեշնչող" },
  { id: "adj-026", label: "հնարավորություններ փնտրող (մոտիվացնող)" },
  { id: "adj-027", label: "խելացի" },
  { id: "adj-028", label: "ինքնագիտակից" },
  { id: "adj-029", label: "ինքնամփոփ" },
  { id: "adj-030", label: "ուժեղ ինտուիցիա ունեցող" },
  { id: "adj-031", label: "բարձր ինքնատիրապետում ունեցող" },
  { id: "adj-032", label: "ինքնավստահ" },
  { id: "adj-033", label: "բարի" },
  { id: "adj-034", label: "զգայուն" },
  { id: "adj-035", label: "համարձակ" },
  { id: "adj-036", label: "բանիմաց" },
  { id: "adj-037", label: "էմոցիոնալ" },
  { id: "adj-038", label: "վատատես" },
  { id: "adj-039", label: "քննադատ" },
  { id: "adj-040", label: "լավ ունկնդիր" },
  { id: "adj-041", label: "ամաչկոտ" },
  { id: "adj-042", label: "վճռական" },
  { id: "adj-043", label: "ինքնահավան" },
  { id: "adj-044", label: "վերլուծական մտածողություն ունեցող" },
  { id: "adj-045", label: "խստապահանջ" },
  { id: "adj-046", label: "սիրալիր" },
  { id: "adj-047", label: "ուրիշներից կախված" },
  { id: "adj-048", label: "հավատարիմ" },
  { id: "adj-049", label: "ինքնաբուխ" },
  { id: "adj-050", label: "արժանապատիվ" },
  { id: "adj-051", label: "հասուն" },
  { id: "adj-052", label: "դիվանագետ" },
  { id: "adj-053", label: "դաժան" },
  { id: "adj-054", label: "համեստ" },
  { id: "adj-055", label: "զրուցասեր" },
  { id: "adj-056", label: "անպատասխանատու" },
  { id: "adj-057", label: "չհարմարվող" },
  { id: "adj-058", label: "ծույլ" },
  { id: "adj-059", label: "կարեկցող" },
  { id: "adj-060", label: "խրախուսող" },
  { id: "adj-061", label: "նյարդային" },
  { id: "adj-062", label: "լարված" },
  { id: "adj-063", label: "մեծ էներգիա ունեցող" },
  { id: "adj-064", label: "ուշադիր" },
  { id: "adj-065", label: "հավասարակշռված" },
  { id: "adj-066", label: "բաց" },
  { id: "adj-067", label: "շփվող" },
  { id: "adj-068", label: "կազմակերպված" },
  { id: "adj-069", label: "ջերմ" },
  { id: "adj-070", label: "ճկուն" },
  { id: "adj-071", label: "իմաստուն" },
  { id: "adj-072", label: "ընկերական" },
  { id: "adj-073", label: "համոզիչ" },
  { id: "adj-074", label: "դժգոհ" },
  { id: "adj-075", label: "բռնկուն/իմպուլսիվ" },
  { id: "adj-076", label: "կոնֆլիկտները հարթող" },
  { id: "adj-077", label: "ավտորիտար" },
  { id: "adj-079", label: "հավակնոտ" },
  { id: "adj-080", label: "անհանգիստ" },
  { id: "adj-081", label: "անբարեխիղճ" },
  { id: "adj-082", label: "աշխույժ" },
  { id: "adj-083", label: "քաղաքավարի" },
  { id: "adj-084", label: "զվարճալի" },
  { id: "adj-085", label: "գերիշխող" },
  { id: "adj-086", label: "ուժեղ կամքով" },
  { id: "adj-087", label: "տաքարյուն" },
  { id: "adj-088", label: "տագնապային" },
  { id: "adj-089", label: "ականավոր" },
  { id: "adj-090", label: "ամբարտավան" },
  { id: "adj-091", label: "դանդաղկոտ" },
  { id: "adj-092", label: "ներդաշնակ" },
  { id: "adj-093", label: "հնարամիտ" },
  { id: "adj-094", label: "շատախոս" },
  { id: "adj-095", label: "հյուրընկալ" },
  { id: "adj-096", label: "կոպիտ" },
  { id: "adj-097", label: "տխուր" },
  { id: "adj-098", label: "ակտիվ" },
  { id: "adj-099", label: "բարեսիրտ" },
  { id: "adj-100", label: "խորամանկ" },
  { id: "adj-101", label: "ագահ" },
  { id: "adj-102", label: "նախանձոտ" },
  { id: "adj-103", label: "խորհրդավոր" },
  { id: "adj-104", label: "մտախոհ" },
  { id: "adj-105", label: "վրեժխնդիր" },
  { id: "adj-106", label: "անկեղծ" },
  { id: "adj-107", label: "քմահաճ" },
  { id: "adj-108", label: "պահպանողական" },
  { id: "adj-109", label: "պերճախոս" },
  { id: "adj-110", label: "ճարպիկ" },
  { id: "adj-111", label: "դաստիարակված" },
  { id: "adj-112", label: "մելամաղձոտ" },
  { id: "adj-113", label: "մռայլ" },
  { id: "adj-114", label: "փափուկ" },
  { id: "adj-115", label: "հուսալի" },
  { id: "adj-116", label: "միամիտ" },
  { id: "adj-117", label: "հաստատակամ" },
  { id: "adj-118", label: "ծաղրող" },
  { id: "adj-119", label: "համառ" },
  { id: "adj-120", label: "զգուշավոր" },
  { id: "adj-121", label: "բարոյական" },
  { id: "adj-122", label: "անփույթ" },
  { id: "adj-123", label: "անզգույշ" },
  { id: "adj-124", label: "արտասովոր" },
  { id: "adj-125", label: "կեղծավոր" },
  { id: "adj-126", label: "անկազմակերպ" },
  { id: "adj-127", label: "ուղիղ" },
  { id: "adj-128", label: "անվճռական" },
  { id: "adj-129", label: "անհամեստ" },
  { id: "adj-130", label: "անարդար" },
  { id: "adj-131", label: "անհամբեր" },
  { id: "adj-132", label: "դիմացկուն" },
  { id: "adj-133", label: "անզիջող" },
  { id: "adj-134", label: "բծախնդիր" }
] as const;
